version: "2"
services:
  elasticsearch:
    #image: hub.c.163.com/library/elasticsearch:5
    image: kimpa0107/elasticsearch:5.6.16-alpine
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./data/:/usr/share/elasticsearch/data/
      - ./config/:/usr/share/elasticsearch/config/
  kibana:
    #image: hub.c.163.com/library/kibana:5.5.2
    image: kimpa0107/kibana:5.5.2
    container_name: kibana
    ports:
      - "5601:5601"
